truncate table PRE_STG_GEOGRAFIA;
truncate table PRE_STG_PRODUCTS;
truncate table STG_DIM_EMPLOYEES;
truncate table stg_dim_customers;
truncate table stg_dim_geografia;
truncate table stg_dim_products;
truncate table stg_dim_shippers;
truncate table stg_dim_tiempo;
truncate table stg_fact_orders;
commit;