
truncate table shippers; 
INSERT INTO SHIPPERS ( SHIPPERID, COMPANYNAME, PHONE ) VALUES ( 
1, 'Speedy Express', '(503) 555-9831'); 
INSERT INTO SHIPPERS ( SHIPPERID, COMPANYNAME, PHONE ) VALUES ( 
2, 'United Package', '(503) 555-3199'); 
INSERT INTO SHIPPERS ( SHIPPERID, COMPANYNAME, PHONE ) VALUES ( 
3, 'Federal Shipping', '(503) 555-9931'); 
commit;