--------------------------------------------------------
--  File created - Sunday-April-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DIM_CUSTOMERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ORDENES_STAR"."DIM_CUSTOMERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DIM_GEOGRAFIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ORDENES_STAR"."DIM_GEOGRAFIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table DIM_CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAR"."DIM_CUSTOMERS" 
   (	"CUSTOMER_IDW" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CUSTOMER_ID" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"CONTACT_NAME" VARCHAR2(200 BYTE), 
	"CONTACT_TITLE" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"CITY" VARCHAR2(200 BYTE), 
	"REGION" VARCHAR2(200 BYTE), 
	"POSTALCODE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(200 BYTE), 
	"FAX" VARCHAR2(100 BYTE), 
	"CURRENT_FLAG" NUMBER(*,0) DEFAULT 1, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATED_DW" DATE DEFAULT SYSDATE, 
	"UPDATED_DW" DATE DEFAULT SYSDATE, 
	"USER_DW" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "ORDENES_STAR"."DIM_CUSTOMERS" TO "ORDENES_STAGE";
  GRANT INSERT ON "ORDENES_STAR"."DIM_CUSTOMERS" TO "ORDENES_STAGE";
  GRANT SELECT ON "ORDENES_STAR"."DIM_CUSTOMERS" TO "ORDENES_STAGE";
  GRANT UPDATE ON "ORDENES_STAR"."DIM_CUSTOMERS" TO "ORDENES_STAGE";
--------------------------------------------------------
--  DDL for Table DIM_EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAR"."DIM_EMPLOYEES" 
   (	"EMPLOYEE_IDW" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLOYEE_ID" NUMBER, 
	"LAST_NAME" VARCHAR2(200 BYTE), 
	"FIRST_NAME" VARCHAR2(200 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"TITLE_OF_COURTESY" VARCHAR2(100 BYTE), 
	"BIRTH_DATE" DATE, 
	"HIRE_DATE" DATE, 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"CITY" VARCHAR2(200 BYTE), 
	"REGION" VARCHAR2(100 BYTE), 
	"POSTALCODE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(200 BYTE), 
	"HOME_PHONE" VARCHAR2(200 BYTE), 
	"EXTENSION" VARCHAR2(100 BYTE), 
	"NOTES" VARCHAR2(2000 BYTE), 
	"REPORTS_TO" NUMBER, 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE, 
	"USER_DW" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "ORDENES_STAR"."DIM_EMPLOYEES" TO "ORDENES_STAGE";
  GRANT INSERT ON "ORDENES_STAR"."DIM_EMPLOYEES" TO "ORDENES_STAGE";
  GRANT SELECT ON "ORDENES_STAR"."DIM_EMPLOYEES" TO "ORDENES_STAGE";
  GRANT UPDATE ON "ORDENES_STAR"."DIM_EMPLOYEES" TO "ORDENES_STAGE";
--------------------------------------------------------
--  DDL for Table DIM_GEOGRAFIA
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAR"."DIM_GEOGRAFIA" 
   (	"CITY" VARCHAR2(100 BYTE), 
	"POSTALCODE" VARCHAR2(100 BYTE), 
	"REGION" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"CREATED_DW" DATE DEFAULT SYSDATE, 
	"UPDATED_DW" DATE DEFAULT SYSDATE, 
	"USER_DWH" VARCHAR2(100 BYTE), 
	"GEOGRAFIA_IDW" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "ORDENES_STAR"."DIM_GEOGRAFIA" TO "ORDENES_STAGE";
  GRANT INSERT ON "ORDENES_STAR"."DIM_GEOGRAFIA" TO "ORDENES_STAGE";
  GRANT SELECT ON "ORDENES_STAR"."DIM_GEOGRAFIA" TO "ORDENES_STAGE";
  GRANT UPDATE ON "ORDENES_STAR"."DIM_GEOGRAFIA" TO "ORDENES_STAGE";
--------------------------------------------------------
--  DDL for Table DIM_PRODUCTS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAR"."DIM_PRODUCTS" 
   (	"PRODUCT_IDW" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"QUANTITY_PER_UNIT" VARCHAR2(200 BYTE), 
	"UNIT_PRICE" NUMBER, 
	"UNITS_IN_STOCK" NUMBER, 
	"UNITS_ON_ORDER" NUMBER, 
	"REORDER_LEVEL" NUMBER, 
	"DISCONTINUED" NUMBER(*,0), 
	"CATEGORY_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(200 BYTE), 
	"CATEGORY_DESCRIPTION" VARCHAR2(200 BYTE), 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(200 BYTE), 
	"SUPPLIER_CONTACT" VARCHAR2(200 BYTE), 
	"SUPPLIER_TITLE" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"CITY" VARCHAR2(200 BYTE), 
	"REGION" VARCHAR2(200 BYTE), 
	"POSTALCODE" VARCHAR2(200 BYTE), 
	"COUNTRY" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(100 BYTE), 
	"FAX" VARCHAR2(100 BYTE), 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE, 
	"USER_DW" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "ORDENES_STAR"."DIM_PRODUCTS" TO "ORDENES_STAGE";
  GRANT INSERT ON "ORDENES_STAR"."DIM_PRODUCTS" TO "ORDENES_STAGE";
  GRANT SELECT ON "ORDENES_STAR"."DIM_PRODUCTS" TO "ORDENES_STAGE";
  GRANT UPDATE ON "ORDENES_STAR"."DIM_PRODUCTS" TO "ORDENES_STAGE";
--------------------------------------------------------
--  DDL for Table DIM_SHIPPERS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAR"."DIM_SHIPPERS" 
   (	"SHIPPER_IDW" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SHIPPER_ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(100 BYTE), 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE, 
	"USER_DW" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "ORDENES_STAR"."DIM_SHIPPERS" TO "ORDENES_STAGE";
  GRANT INSERT ON "ORDENES_STAR"."DIM_SHIPPERS" TO "ORDENES_STAGE";
  GRANT SELECT ON "ORDENES_STAR"."DIM_SHIPPERS" TO "ORDENES_STAGE";
  GRANT UPDATE ON "ORDENES_STAR"."DIM_SHIPPERS" TO "ORDENES_STAGE";
--------------------------------------------------------
--  DDL for Table DIM_TIEMPO
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAR"."DIM_TIEMPO" 
   (	"FECHA" DATE, 
	"DIA" NUMBER(10,0), 
	"DIA_SEMANA_CORTO" VARCHAR2(10 BYTE), 
	"DIA_SEMANA" VARCHAR2(10 BYTE), 
	"DIA_LABORAL" VARCHAR2(10 BYTE), 
	"DIA_FERIADO" VARCHAR2(10 BYTE), 
	"SEMANA_MES" NUMBER(10,0), 
	"SEMANA_ANIO" NUMBER(10,0), 
	"MES" NUMBER(10,0), 
	"MES_CADENA" VARCHAR2(10 BYTE), 
	"PERIODO" VARCHAR2(10 BYTE), 
	"TRIMESTRE" VARCHAR2(10 BYTE), 
	"SEMESTRE" VARCHAR2(10 BYTE), 
	"ANIO" NUMBER(10,0), 
	"USER_DW" VARCHAR2(100 BYTE), 
	"CREATED_DW" DATE DEFAULT SYSDATE, 
	"UPDATED_DW" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "ORDENES_STAR"."DIM_TIEMPO" TO "ORDENES_STAGE";
  GRANT INSERT ON "ORDENES_STAR"."DIM_TIEMPO" TO "ORDENES_STAGE";
  GRANT SELECT ON "ORDENES_STAR"."DIM_TIEMPO" TO "ORDENES_STAGE";
  GRANT UPDATE ON "ORDENES_STAR"."DIM_TIEMPO" TO "ORDENES_STAGE";
--------------------------------------------------------
--  DDL for Table FACT_ORDERS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAR"."FACT_ORDERS" 
   (	"ORDER_DATE" DATE, 
	"USER_DW" VARCHAR2(200 BYTE), 
	"CREATED_DW" DATE DEFAULT SYSDATE, 
	"UPDATED_DW" DATE DEFAULT SYSDATE, 
	"REQUIRED_DATE" DATE, 
	"SHIPPED_DATE" DATE, 
	"SHIP_VIA" NUMBER(*,0), 
	"SHIP_NAME" VARCHAR2(200 BYTE), 
	"UNIT_PRICE" NUMBER(*,2), 
	"QUANTITY" NUMBER(*,0), 
	"DISCOUNT" NUMBER(*,2), 
	"CUSTOMER_IDW" NUMBER, 
	"EMPLOYEE_IDW" NUMBER, 
	"PRODUCT_IDW" NUMBER, 
	"SHIPPER_IDW" NUMBER, 
	"GEOGRAFIA_IDW" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "ORDENES_STAR"."FACT_ORDERS" TO "ORDENES_STAGE";
  GRANT INSERT ON "ORDENES_STAR"."FACT_ORDERS" TO "ORDENES_STAGE";
  GRANT SELECT ON "ORDENES_STAR"."FACT_ORDERS" TO "ORDENES_STAGE";
  GRANT UPDATE ON "ORDENES_STAR"."FACT_ORDERS" TO "ORDENES_STAGE";