--------------------------------------------------------
--  DDL for Table LOG_DE_PROCESOS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."LOG_DE_PROCESOS" 
   (	"NOMBRE_PROCESO" VARCHAR2(50 BYTE), 
	"FEC_INICIO" DATE, 
	"FEC_FIN" DATE, 
	"COMENTARIO" VARCHAR2(500 BYTE), 
	"CANT_REG" NUMBER, 
	"CORRECTO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRE_STG_GEOGRAFIA
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."PRE_STG_GEOGRAFIA" 
   (	"CITY" VARCHAR2(15 BYTE), 
	"REGION" VARCHAR2(15 BYTE), 
	"POSTALCODE" VARCHAR2(10 BYTE), 
	"COUNTRY" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRE_STG_PRODUCTS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."PRE_STG_PRODUCTS" 
   (	"PRODUCT_ID" NUMBER(38,0), 
	"NAME" VARCHAR2(40 BYTE), 
	"QUANTITY_PER_UNIT" VARCHAR2(20 BYTE), 
	"UNIT_PRICE" NUMBER(19,2), 
	"UNITS_IN_STOCK" NUMBER(5,0), 
	"UNITS_ON_ORDER" NUMBER(5,0), 
	"REORDER_LEVEL" NUMBER(5,0), 
	"DISCONTINUED" NUMBER(1,0), 
	"CATEGORY_ID" NUMBER(38,0), 
	"CATEGORY_NAME" VARCHAR2(15 BYTE), 
	"CATEGORY_DESCRIPTION" VARCHAR2(50 BYTE), 
	"SUPPLIER_ID" NUMBER(38,0), 
	"SUPPLIER_NAME" VARCHAR2(40 BYTE), 
	"SUPPLIER_CONTACT" VARCHAR2(30 BYTE), 
	"SUPPLIER_TITLE" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(60 BYTE), 
	"CITY" VARCHAR2(15 BYTE), 
	"REGION" VARCHAR2(15 BYTE), 
	"POSTALCODE" VARCHAR2(10 BYTE), 
	"COUNTRY" VARCHAR2(15 BYTE), 
	"PHONE" VARCHAR2(24 BYTE), 
	"FAX" VARCHAR2(24 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STG_DIM_CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."STG_DIM_CUSTOMERS" 
   (	"CUSTOMER_IDW" NUMBER, 
	"CUSTOMER_ID" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"CONTACT_NAME" VARCHAR2(200 BYTE), 
	"CONTACT_TITLE" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"CITY" VARCHAR2(200 BYTE), 
	"REGION" VARCHAR2(200 BYTE), 
	"POSTALCODE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(200 BYTE), 
	"FAX" VARCHAR2(100 BYTE), 
	"CURRENT_FLAG" NUMBER(*,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE, 
	"USER_DW" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STG_DIM_EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."STG_DIM_EMPLOYEES" 
   (	"EMPLOYEE_IDW" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"LAST_NAME" VARCHAR2(200 BYTE), 
	"FIRST_NAME" VARCHAR2(200 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"TITLE_OF_COURTESY" VARCHAR2(100 BYTE), 
	"BIRTH_DATE" DATE, 
	"HIRE_DATE" DATE, 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"CITY" VARCHAR2(200 BYTE), 
	"REGION" VARCHAR2(100 BYTE), 
	"POSTALCODE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(200 BYTE), 
	"HOME_PHONE" VARCHAR2(200 BYTE), 
	"EXTENSION" VARCHAR2(100 BYTE), 
	"NOTES" VARCHAR2(2000 BYTE), 
	"REPORTS_TO" NUMBER, 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE, 
	"USER_DW" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STG_DIM_GEOGRAFIA
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."STG_DIM_GEOGRAFIA" 
   (	"GEOGRAFIA_IDW" NUMBER(10,0), 
	"CITY" VARCHAR2(100 BYTE), 
	"POSTALCODE" VARCHAR2(100 BYTE), 
	"REGION" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE, 
	"USER_DWH" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STG_DIM_PRODUCTS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."STG_DIM_PRODUCTS" 
   (	"PRODUCT_IDW" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"QUANTITY_PER_UNIT" VARCHAR2(200 BYTE), 
	"UNIT_PRICE" NUMBER, 
	"UNITS_IN_STOCK" NUMBER, 
	"UNITS_ON_ORDER" NUMBER, 
	"REORDER_LEVEL" NUMBER, 
	"DISCONTINUED" NUMBER(*,0), 
	"CATEGORY_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(200 BYTE), 
	"CATEGORY_DESCRIPTION" VARCHAR2(200 BYTE), 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(200 BYTE), 
	"SUPPLIER_CONTACT" VARCHAR2(200 BYTE), 
	"SUPPLIER_TITLE" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"CITY" VARCHAR2(200 BYTE), 
	"REGION" VARCHAR2(200 BYTE), 
	"POSTALCODE" VARCHAR2(200 BYTE), 
	"COUNTRY" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(100 BYTE), 
	"FAX" VARCHAR2(100 BYTE), 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE, 
	"USER_DW" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STG_DIM_SHIPPERS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."STG_DIM_SHIPPERS" 
   (	"SHIPPER_IDW" NUMBER, 
	"SHIPPER_ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(100 BYTE), 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE, 
	"USER_DW" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STG_DIM_TIEMPO
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."STG_DIM_TIEMPO" 
   (	"FECHA" DATE, 
	"DIA" NUMBER(10,0), 
	"DIA_SEMANA_CORTO" VARCHAR2(10 BYTE), 
	"DIA_SEMANA" VARCHAR2(10 BYTE), 
	"DIA_LABORAL" VARCHAR2(10 BYTE), 
	"DIA_FERIADO" VARCHAR2(10 BYTE), 
	"SEMANA_MES" NUMBER(10,0), 
	"SEMANA_ANIO" NUMBER(10,0), 
	"MES" NUMBER(10,0), 
	"MES_CADENA" VARCHAR2(10 BYTE), 
	"PERIODO" VARCHAR2(10 BYTE), 
	"TRIMESTRE" VARCHAR2(10 BYTE), 
	"SEMESTRE" VARCHAR2(10 BYTE), 
	"ANIO" NUMBER(10,0), 
	"USER_DW" VARCHAR2(100 BYTE), 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STG_FACT_ORDERS
--------------------------------------------------------

  CREATE TABLE "ORDENES_STAGE"."STG_FACT_ORDERS" 
   (	"ORDER_DATE" DATE, 
	"USER_DW" VARCHAR2(200 BYTE), 
	"CREATED_DW" DATE, 
	"UPDATED_DW" DATE, 
	"REQUIRED_DATE" DATE, 
	"SHIPPED_DATE" DATE, 
	"SHIP_VIA" NUMBER(*,0), 
	"SHIP_NAME" VARCHAR2(200 BYTE), 
	"UNIT_PRICE" NUMBER(*,2), 
	"QUANTITY" NUMBER(*,0), 
	"DISCOUNT" NUMBER(*,2), 
	"CUSTOMER_IDW" NUMBER, 
	"EMPLOYEE_IDW" NUMBER, 
	"PRODUCT_IDW" NUMBER, 
	"SHIPPER_IDW" NUMBER, 
	"GEOGRAFIA_IDW" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
